export const MenuItems = [
  {
    src: "/icon/sun.svg",
    url: "/pagi",
    CnameLg: "w-auto h-8",
    CnameSm: "w-auto h-6",
    sm: "flex flex-row px-3 py-2 text-gray-600",
    title: "dzikir pagi",
    border: "pb-2 border-b-2 border-fuchsia-600",
  },
  {
    src: "/icon/sunrise.svg",
    url: "/petang",
    CnameLg: "w-auto h-7",
    CnameSm: "w-auto h-5",
    sm: "flex flex-row px-3 py-2 text-gray-600",
    title: "dzikir petang",
    border: "py-2 pb-2 border-b-2 border-fuchsia-600",
  },
  {
    src: "/icon/cloud.svg",
    url: "/sholat",
    CnameLg: "w-auto h-9",
    CnameSm: "w-auto h-6",
    sm: "flex flex-row px-3 py-2 text-gray-600",
    title: "dzikir setelah sholat",
    border: "py-2 pb-2 border-b-2 items-center border-fuchsia-600",
  },
  {
    src: "/icon/sleep.svg",
    url: "/tidur",
    CnameLg: "w-auto h-7",
    CnameSm: "w-auto h-5",
    sm: "flex flex-row px-3 py-2 text-gray-600",
    title: "dzikir sebelum tidur",
    border: "py-2 pb-1",
  },
];
